ALTER TABLE trips ADD COLUMN IF NOT EXISTS entities_json TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS supported_currencies_json TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS participant_count INTEGER;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_notes TEXT;
